name: Publish

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: jdx/mise-action@v2
      - name: Check formatting
        run: deno fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: jdx/mise-action@v2
      - name: Check linting
        run: deno lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: jdx/mise-action@v2
      - name: Publish
        run: deno test -A
