name: Publish

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: jdx/mise-action@v2
      - name: Publish
        run: deno test -A
