name: CI

on:
  push:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: jdx/mise-action@v2
      - name: Check formatting
        run: deno fmt --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: jdx/mise-action@v2
      - name: Check linting
        run: deno lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: jdx/mise-action@v2
      - name: Run tests
        run: deno test -A

  publish:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - format
      - lint
      - test
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: jdx/mise-action@v2
      - name: Publish to JSR
        run: deno publish
